function [] = end_practice(window, screenYpixels)
%%% displays instructions for the end of practice

Screen('TextStyle', window, 1);
Screen('TextSize', window, 20);
instruct_col = [255, 255, 255];
instructions = ...
    sprintf(['Well done! \n\n'...
    'From now on, the animals will be hiding in two different\n'...
    'coloured houses.\n\n'...
    'Your task is to find the animal is 6 moves or less.\n\n'...
    'In each house, animals have a different set of preferred hiding places,\n'...
    'and they will only hide in these locations.\n\n'...
    'You need to learn the animals` hiding places to complete the task.\n\n'...
    'Press any key to continue...']);
    DrawFormattedText(window, instructions,'Center', screenYpixels*.3, instruct_col);
    Screen('Flip', window);
    KbWait();
    WaitSecs(0.5);

   instructions = ...
    sprintf(['You will hear some tones each time you find an animal in 6 moves or less\n\n'...
    'Listen to the tones to track how well you are doing.\n'...
    'The more tones you hear, the better you did!\n\n ' ... 
    'Press any key to see the first house. Good luck!']);
    DrawFormattedText(window, instructions,'Center', screenYpixels*.3, instruct_col);
    Screen('Flip', window);
end