function [] = end_practice(window, screenYpixels)
%%% displays instructions for the end of practice

Screen('TextStyle', window, 1);
Screen('TextSize', window, 20);
instructions = ...
    sprintf(['Well done! \n\n'...
    'From now on, the animals will be hiding in two different\n'...
    'coloured houses.\n\n'...
    'You can tell which house you are in by the colour of the border\n\n'...
    'The animals will be hiding in a different set of rooms, depending on which house they are in.\n\n'...
    'Your task is to learn to find the animal within 6 moves or less.\n ' ...
    'You must learn the hiding places to complete this stage of the task.\n\n'...
    'You will hear some tones when you find the animal in 6 moves or less.\n'...
    'Listen for the tones to track how you are doing. The more tones you hear, \n'...
    'the better you did! \n\n'...
    'The more tones you hear, the better you did.\n\n'... 
    'Press any key to start the task. Good luck!']);
    DrawFormattedText(window, instructions,'Center', screenYpixels*.3, [0 0 255]);
    Screen('Flip', window);
end