function [] = run_instructions(window, screenYpixels, stage, experiment, house)

if stage == 1 
    if house == 1
    instructions = ...
        sprintf(['Animals are playing hide & seek in a house with 24 rooms.\n\n'...
                 'Your task is to find the animals hiding in these rooms. \n\n'...
                 'At the start of each trial, you will see a black dot in \n'...
                 'the centre of the screen. You must click on this black dot \n'...
                 'before you can look inside the rooms. \n\n' ...
                 'To look inside the rooms, click on any of the doors on the screen. \n\n'...
                 'Press any key to see the doors and have a practice.\n']);
    elseif house == 2
      instructions = ...
        sprintf(['Well done!\n\n'...
                 'That was just the first house. You will now see the next house. \n\n' ...
                 'Remember to try and find the animals in 6 moves or less.\n\n' ...
                 'Press any key to see the next house. Good luck! \n']);
    elseif house == 9
      instructions = ...
        sprintf(['Good job! You`ve now seen both houses. \n\n'...
                 'Let`s see how familiar you are with the animals` hiding places. \n\n' ...
                 'For each house, click on the doors that the animals like to hide behind. \n\n' ...
                 'Try to be as accurate as you can. \n\n' ...
                 'Press any key to start. \n']);
    end
elseif stage == 2 
    instructions = ...
        sprintf(['Nice work!\n\n' ...
        'Now, it will be more difficult to tell which house you are in.\n'...
        'You must remember the animals hiding places, so that \n'...
        'you know which house you are in\n\n' ...
        'The house will change from time to time. However you are \n' ...
        'always more likely to remain in the same house than \n' ...
        'move to another on the next trial.\n\n' ...
        'Keep trying to find the animals within 4 moves.\n' ...
        'The good news is that now each time you hear the tones, you will win points!\n'...,
        'Points will convert to cold hard cash bonuses!\n'...
        'You will reap rewards when you find the animal in 4 moves or less.\n'...
        '1 move = 4 points\n'...
        '2 moves = 3 points\n'...
        '3 moves = 2 points\n'...
        '4 moves = 1 points\n\n'...
        'You will know how many points you won from how many tones you hear.\n\n'...
        'Note that points will not be available on every trial. If you get the animal\n'...
        'In less than 4 moves and you don`t hear a sound, then there were no points that\n'...
        'time\n'...
        'Remember that points become sweet cash!']);
elseif stage == 3 && experiment == 1
    instructions = ...
        sprintf(['Way to go!\n\n' ...
        'Now, you will be able to use the colours to tell \n' ...
        'you which house you are in.\n\n' ...
        'Press any key to start. Good luck!']);
elseif stage == 3 && experiment == 2
    instructions = ...
        sprintf(['Way to go!\n\n' ...
        'Now, the animals have moved to two new houses.\n' ...
        'Your task is still to find the animals.\n\n' ...
        'It may help to use their previous hiding \n' ...
        'places to find them.\n\n' ...
        'Press any key to start. Good luck!']);
end
Screen('TextStyle', window, 1);
Screen('TextSize', window, 20);

DrawFormattedText(window, instructions,'Center', screenYpixels*.3, [0 0 255]);
Screen('Flip', window);

end