function [] = run_instructions(window, screenYpixels, stage, house,...
    badge_rects, badge_tex, points_structure)

Screen('TextStyle', window, 1);
Screen('TextSize', window, 20);
instruct_col = [255, 255, 255];

if stage == 1 
    if house == 1
    instructions = ...
        sprintf(['Animals are playing hide & seek in a house with 24 rooms.\n\n'...
                 'Your task is to find the animals hiding in these rooms. \n\n'...
                 'At the start of each trial, you will see a black dot in \n'...
                 'the centre of the screen. You must click on this black dot \n'...
                 'before you can look inside the rooms. \n\n' ...
                 'To look inside the rooms, click on any of the doors on the screen. \n\n'...
                 'Press any key to see the doors and have a practice.\n']);
    elseif house == 2
      instructions = ...
        sprintf(['Well done!\n\n'...
                 'That was just the first house. You will now see the next house. \n\n' ...
                 'Remember to try and find the animals in 6 moves or less.\n\n' ...
                 'Keep listening to the tones to track how well you are doing.\n\n' ...
                 'Press any key to see the next house. Good luck! \n']);
    elseif house == 9
      instructions = ...
        sprintf(['Good job! You`ve now seen both houses. \n\n'...
                 'Let`s see how familiar you are with the animals` hiding places. \n\n' ...
                 'For each house, click on the doors that the animals like to hide behind. \n\n' ...
                 'Try to be as accurate as you can. \n\n' ...
                 'Press any key to start. \n']);
    end
elseif stage == 2 
    instructions = ...
        sprintf(['Nice work!\n\n' ...
        'Now, it will be more difficult to tell which house you are in.\n'...
        'The coloured borders have been stolen! \n' ...
        'You must remember the animals hiding places, so that \n'...
        'you know which house you are in\n\n' ...
        'The house will change from time to time. However you are \n' ...
        'always more likely to remain in the same house than \n' ...
        'move to another on the next trial.\n\n' ...
        'Keep trying to find the animals within 6 moves.\n' ...
        'Press any key to continue.']);
    DrawFormattedText(window, instructions,'Center', screenYpixels*.3, instruct_col);
    Screen('Flip', window);
    KbWait();
    WaitSecs(0.5);

    instructions = ...
        sprintf(['Now for the exciting news!' ...
        'You have a chance of winning ˖⁺‧₊˚✦ points! ✦˖⁺‧₊˚ \n' ...
        'Buuuut ONLY if you find the animal within 6 moves.\n\n'...
        'Every time you hear a tone, that means you won 100 points!\n\n\n'...,
        'Note that points will not be available on every trial. If you get the animal\n'...
        'in 6 moves or less and you don`t hear a sound, then there were no points.\n\n\n\n'...
        'Now, press any key to learn what these points will earn you!']);
    DrawFormattedText(window, instructions,'Center', screenYpixels*.3, instruct_col);
    Screen('Flip', window);
    KbWait();
    WaitSecs(0.5);

    instructions = ...
        sprintf(['If you win enough points, you can unlock some coveted badges!\n\n\n'...
        '%d points = Bronze Badge achieved\n'...
        '%d = Silver Badge attained\n'...
        '%d = Gold Badge unlocked\n'...
        '%d points = The rare Champion Badge will have your name written all over it!\n\n\n'...
        'You think you can reach Champion status, young participant?\n\n'...
        'Many pass through these Mathews building doors, yet not many can call themselves Champions...\n\n\n\n'...
        'Press any key to start the task.'], points_structure(1), points_structure(2),...
        points_structure(3), points_structure(4));
    draw_badges(window, [1, 1, 1, 1], badge_rects, badge_tex);


elseif stage == 3 
    instructions = ...
        sprintf(['Way to go!\n\n' ...
        'Now, the animals have moved to three new houses.\n' ...
        'We`re bringing the colour back, so you can tell \n' ...
        'which house you`re in by the colour of the border.\n\n'...
        'Keep trying to find the animals in 6 moves or less.\n\n' ...
        'Press any key to see the first new house.\n\n' ...
        'Good luck!']);
end

if stage == 2
    shift_txt = .5;
else
    shift_txt = .3;
end
DrawFormattedText(window, instructions,'Center', screenYpixels*shift_txt, instruct_col);
Screen('Flip', window);


end