function [] = end_practice(window, screenYpixels)
%%% displays instructions for the end of practice

Screen('TextStyle', window, 1);
Screen('TextSize', window, 20);
instructions = ...
    sprintf(['Well done! \n\n'...
    'From now on, the animals will be hiding in two different\n'...
    'coloured houses.\n\n'...
    'The animals will be hiding in different rooms, depending on which house they are in.\n\n'...
    'You must learn these hiding places to complete the task.\n\n'...
    'Your task is to learn to find the animal within 4 moves. \n ' ...
    'You will reap rewards when you find the animal in 4 moves or less.\n'...
    '1 move = 4 points\n'...
    '2 moves = 3 points\n'...
    '3 moves = 2 points\n'...
    '1 move = 1 points\n\n'...
    'You will know how many points you won from how many tones you hear.\n\n'...
    'No points will be awarded if you take more than 4 moves to find the animals :( \n\n'...
    'Remember to try and find the animal within 4 moves on every trial.\n'...
    'At first, this will be tough but will become easy once you learn their hiding places.\n\n'... 
    'Press any key to start the task. Good luck!']);
    DrawFormattedText(window, instructions,'Center', screenYpixels*.3, [0 0 255]);
    Screen('Flip', window);
end