function [] = run_instructions(window, screenYpixels, stage, experiment)

if stage == 1 
    instructions = ...
        sprintf(['Animals are playing hide & seek in a house with 16 rooms.\n\n'...
                 'Your task is to find the animals hiding in these rooms. \n\n'...
                 'You will click on a door to look inside a room.\n\n'...
                 'Press any key to see the doors and have a practice.\n']);
elseif stage == 2 
    instructions = ...
        sprintf(['Nice work!\n\n' ...
        'Now, it will be more difficult to tell which house you are in.\n'...
        'You must remember the animals hiding places, so that \n'...
        'you know which house you are in\n\n' ...
        'The house will change from time to time. However you are \n' ...
        'always more likely to remain in the same house than \n' ...
        'move to another on the next trial.\n\n' ...
        'Keep trying to find the animals within 4 moves.\n' ...
        'You will continue to earn points, however, points will \n' ...
        'sometimes not be available. \n\n' ...
        'Remember that points become sweet cash!']);
elseif stage == 3 && experiment == 1
    instructions = ...
        sprintf(['Way to go!\n\n' ...
        'Now, you will be able to use the colours to tell \n' ...
        'you which house you are in.\n\n' ...
        'Press any key to start. Good luck!']);
elseif stage == 3 && experiment == 2
    instructions = ...
        sprintf(['Way to go!\n\n' ...
        'Now, the animals have moved to two new houses.\n' ...
        'Your task is still to find the animals.\n\n' ...
        'It may help to use their previous hiding \n' ...
        'places to find them.\n\n' ...
        'Press any key to start. Good luck!']);
end
Screen('TextStyle', window, 1);
Screen('TextSize', window, 20);

DrawFormattedText(window, instructions,'Center', screenYpixels*.3, [0 0 255]);
Screen('Flip', window);

end