function [] = end_practice(window, screenYpixels)
%%% displays instructions for the end of practice

Screen('TextStyle', window, 1);
Screen('TextSize', window, 20);
instructions = ...
    sprintf(['Nice work! \n\n'...
    'But here`s where things get interesting\n\n'...
    'From now on, the animals will be hiding in two different\n'...
    'coloured houses.\n\n'...
    'You can tell which house you`re in by looking at the colour\n'...
    'of it`s border.\n\n'...
    'Press any key to learn more about the houses']);
    DrawFormattedText(window, instructions,'Center', screenYpixels*.3, [0 0 255]);
    Screen('Flip', window);
    KbWait()
    WaitSecs(0.5);

 instructions = ...
     sprintf(['Each house has its own favourite hiding spots, and\n' ...
     'the animals love to stick to these rooms.\n\n' ...
     'Remember, the colour border will tell you which house you are in. \n\n' ...
     'Your job is to learn to find the animal within 4 MOVES.\n\n' ...
     'Press any key to continue']);
 DrawFormattedText(window, instructions,'Center', screenYpixels*.3, [0 0 255]);
 Screen('Flip', window);
 KbWait()
 WaitSecs(0.5);

  instructions = ...
     sprintf([
    'You are doing the task correctly when you find the animal in 4 moves or less.\n'...
    'And here`s a cool bonus -\n\n'...
    'You will hear a tone when you`ve done the task well.\n\n'...
    'No tone? That means it took more than 4 moves.\n'...
    'Don`t worry! Try to find the animals in 4 moves next time! :)\n\n'...
    'At first, this task will be tough but will become easy once you learn their hiding places.\n\n'... 
    'Press any key to start learning the first house. Good luck!']);
    DrawFormattedText(window, instructions,'Center', screenYpixels*.3, [0 0 255]);
    Screen('Flip', window);
end