function [] = run_instructions(window, screenYpixels, stage, house)

if stage == 1 
    if house == 1
    instructions = ...
        sprintf(['Animals are playing hide & seek in a house with 16 rooms.\n\n'...
                 'Your task is to find the animals hiding in these rooms. \n\n'...
                 'You will click on a door to look inside a room.\n\n'...
                 'Press any key to see the doors and have a practice.\n']);
    elseif house == 2
      instructions = ...
        sprintf(['Time to learn the next house!\n'...
                'Remember to try and find the animals in 4 moves\n']);
    elseif house == 9
      instructions = ...
        sprintf(['We`re going to go through that one more time\n'...
                'Remember to try and find the animals in 4 moves\n']);
    end
elseif stage == 2 
    instructions = ...
        sprintf(['Nice work!\n\n' ...
        'Now, we are going to do this task for a bit longer\n\n' ...
        'Keep trying to find the animals within 4 moves.\n' ...
        'The good news is that now each time you hear the tones, you will win points!\n'...,
        'Points will convert to cold hard cash bonuses!\n'...
        'You will reap rewards when you find the animal in 4 moves or less.\n'...
        '1 move = 4 points\n'...
        '2 moves = 3 points\n'...
        '3 moves = 2 points\n'...
        '4 moves = 1 points\n\n'...
        'You will know how many points you won from how many tones you hear.\n\n'...
        'Note that points will not be available on every trial. If you get the animal\n'...
        'In less than 4 moves and you don`t hear a sound, then there were no points that\n'...
        'time\n'...
        'Remember that points become sweet cash!']);
elseif stage == 3 
    instructions = ...
        sprintf(['Way to go!\n\n' ...
        'One last go on the task! \n' ...
        'Press any key to start. Good luck!']);
end
Screen('TextStyle', window, 1);
Screen('TextSize', window, 20);

DrawFormattedText(window, instructions,'Center', screenYpixels*.3, [0 0 255]);
Screen('Flip', window);

end