function [] = run_mts_instructions(window, screenYpixels)


instructions = ...
    sprintf(['Breaking news!\n'...
    'The creatures are getting ready for a fun challenge, and they need your help! \n\n'...
    'In a house with 16 rooms, 4 creatures are peeking out from their rooms...\n'...
    'Your task is to remember which creatures are in which rooms.\n\n' ...
    'After that, the house will go quiet, and you`ll see an empty house.\n' ...
    'But don`t worry - the creatures will pop out again!\n\n' ...
    'When the creatures pop out again, if they are in the same rooms\n' ...
    'as before, press S for SAME.\n' ...
    'If they are in different rooms, then press D for DIFFERENT.\n\n' ...
    'Get it right and you`ll see: "Correct :)"\n' ...
    'Get it wrong and you`ll see: "Incorrect :("\n\n' ...
    'At first this might seem tricky, but don`t worry - it`ll get easier\n'...
    'as you go. Pinky promise!\n\n' ...
    'Press any key to begin!\n']);

Screen('TextStyle', window, 1);
Screen('TextSize', window, 20);
DrawFormattedText(window, instructions,'Center', screenYpixels*.3, [0 0 255]);
Screen('Flip', window);

end