function [] = run_instructions(window, screenYpixels, stage, house)

if stage == 1 
    if house == 1
    instructions = ...
        sprintf(['Nice work remembering the creatures!\n\n'...
                 'But now, some new animals have decided to play hide and seek...\n'...
                 'And guess what? You`re "it"!\n\n'...
                 'They`re hiding in the rooms of the house, and your job\n' ...
                 'is to find them.\n\n'...
                 'To look inside a room, just click on a door.\n\n'...
                 'Press any key to explore a house']);
    elseif house == 2
      instructions = ...
        sprintf(['Time to explore the next house!\n\n'...
                 'Let`s try to find the animals in 4 moves or less.\n\n'...
                 'Press any key to continue!\n']);
    elseif house == 9
      instructions = ...
        sprintf(['We`re going to go through that one more time\n'...
                'Remember to try and find the animals in 4 moves\n']);
    end
elseif stage == 2 
    instructions = ...
        sprintf(['Nice work so far!\n\n' ...
        'Now, it`s time to play for a bit longer...and guess what?\n\n' ...
        'You can start winning points\n' ...
        'And with points you unlock badges!\n\n'...,
        'Keep trying to find the animals within 4 moves\n\n'...
        'But here is the exciting part\n'...
        'Every time you hear the tone, that means you`ve earned 100 points!\n\n'...
        'But here is something to keep in mind -\n'...
        'Points won`t be available on every trial, just the bonus trials!\n'...
        'If you find the animal in 4 moves or less but don`t hear a tone\n'...
        'that just means there were no points up for grabs that time. No worries-\n'...
        'you`ll have plenty of chances to score!\n\n'...
        'If you get enough points, you unlock badges!\n\n'...
        '6000 = Bronze Badge Achieved\n'...
        '12,000 = Silver Badge Attained\n'...
        '18,000 = Gold Badge Unlocked\n'...
        '21,600 points = You get the rare Champion Badge!\n\n'...
        'Ready to unlock badges?\n\n'...
        'Press any key to continue!']);
elseif stage == 3 
    instructions = ...
        sprintf(['You`ve done such a great job so far - well done!\n\n' ...
        'Now it`s time for your final challenge, where things get a little trickier\n' ...
        'Press any key to start. Good luck!']);
end
Screen('TextStyle', window, 1);
Screen('TextSize', window, 20);

DrawFormattedText(window, instructions,'Center', screenYpixels*.3, [0 0 255]);
Screen('Flip', window);

end