function [] = end_practice(window, screenYpixels)
%%% displays instructions for the end of practice

Screen('TextStyle', window, 1);
Screen('TextSize', window, 20);
instruct_col = [255 255 255];

instructions = ...
    sprintf(['Good job with that practice round!\n\n\n'...
    'From now on, there are two different coloured houses the animals can hide in.\n\n'...
    'You can tell which house you are looking at by the colour of its border.\n\n\n'...
    'Which animal you will find is random - importantly, your task is to find\n'...
    'their hiding spots in each house! I have a secret tip for you...\n'...
    'I hear they like to hide in the same rooms of that house...\n'...
    'You didn`t hear it from me!\n\n'...
    '(You hear a whisper coming from the trees...\n' ...
    'a windy voice speaks: you must learn the animals` hiding spots in each house to be successful..)\n\n\n',...
    'Try and find each animal within 4 moves.\n\n\n\n'...
    'Press any key to start.']); 
DrawFormattedText(window, instructions,'Center', screenYpixels*.3, instruct_col);
Screen('Flip', window);
end

